### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by mieszkosabo** [softwaremill/walk-that-type#6]
# Roadmap

- [x] format displayed code
- [x] primitive types
- [x] spread operator for tuples (eg. used for concat)
- [ ] infer
  - [x] tuples
  - [x] objects
  - [ ] functions
- [x] object types
- [x] union types
- [x] mapped types
- [x] distributed union
- [x] indexed access types
- [x] keyof
- [ ] template string literals
- [ ] intersection types
- [ ] function types
- [ ] type variance
- [ ] readonly
- [ ] optional properties
- [ ] built-in types
  - [x] Uppercase
  - [x] Lowercase
  - [x] Capitalize
  - [x] Uncapitalize
  - [x] Extract,
  - [x] Exclude
  - [x] Pick,
  - [x] Omit
  - [ ] Partial, Required (needs optional properties)
  - [ ] Readonly (needs readonly)
  - [ ] NonNullable (needs intersection and `{}` type)
  - [ ] Record
  - [ ] Awaited, Promise, PromiseLike
  - [ ] Parameters, ReturnType (needs function types)
- [ ] extends
  - [x] any, unknown, never
  - [x] common sets such as number, string
  - [x] literal types
  - [x] objects
  - [x] union types
  - [ ] intersection types
  - [ ] function types
- [x] conditional types

---

Feel free to comment which features would you like to see first.

Also let me know if there's something you'd like that's not on the list.
